# Netlify Build Configuration

# Ignore builds when only assets change
[build]
  ignore = "git diff --quiet HEAD^ HEAD -- . :^assets/"

# Output directory and 11ty build command
[build]
  publish = "_site"
  command = "eleventy && [ -d _site/preview/admin ] && mv _site/preview/admin/* _site/ && rm -rf _site/preview/admin 2>/dev/null || true"

# Cache generated content between builds (e.g. images)
# https://github.com/jakejarvis/netlify-plugin-cache
[[plugins]]
package = "netlify-plugin-cache"

  # Path to the 11ty cache folder
  [plugins.inputs]
  paths = [ ".cache" ]

# Be aware that if you have conflicting configuration values, settings specified in
# netlify.toml override any corresponding settings in the Netlify UI.

# https://www.netlify.com/docs/netlify-toml-reference/  