name: Sync Assets to Cloudflare R2

env:
  R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
  R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      
on:
  push:
    branches: [master]
    paths:
      - "assets/**"

jobs:

  deploy:
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get all files including assets

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Configure AWS CLI for Cloudflare R2
        run: |
          mkdir -p ~/.aws
          cat << EOF > ~/.aws/credentials
          [default]
          aws_access_key_id = ${{ R2_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ R2_SECRET_ACCESS_KEY }}
          EOF

          cat << EOF > ~/.aws/config
          [default]
          region = auto
          s3 =
            endpoint_url = https://${{ R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
            signature_version = s3v4
          EOF

      - name: Sync assets to Cloudflare R2
        run: |
          # Create a temporary directory and copy only the assets folder
          mkdir -p temp_assets
          cp -r assets/* temp_assets/

          # Sync the assets to Cloudflare R2
          aws s3 sync \
            --delete \
            --acl public-read \
            --cache-control "public, max-age=31536000" \
            temp_assets/ \
            s3://${{ R2_BUCKET_NAME }}/assets/

          # Clean up
          rm -rf temp_assets
